### ISSUE TITLE
只有两级的时候，没有清除原来选择的四级

### ISSUE THREAD

**Issue by zhzw345** [IceApriler/miniprogram-picker#2]
一开始选泽了有一二三四级的选项，然后切换到只有一二级的选项，原来选择的四级没有清除掉
![image](https://user-images.githubusercontent.com/35107007/61840374-87b2ab80-aec3-11e9-80e8-497daed06303.png)

**Comment by IceApriler** [comment]
好的，了解了，之前并没有支持选项少于阶数的情况，我调整一下。

**Comment by IceApriler** [comment]
@zhzw345 你好，能否提供一下可供复现的sourceData？

**Comment by zhzw345** [comment]
好的，附件中就是复现的数据


------------------ 原始邮件 ------------------
发件人: "April"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午2:31
收件人: "IceApriler/miniprogram-picker"<miniprogram-picker@noreply.github.com>;
抄送: "Zhang"<249475586@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [IceApriler/miniprogram-picker] 只有两级的时候，没有清除原来选择的四级 (#2)




@zhzw345 你好，能否提供一下可供复现的sourceData？

**Comment by zhzw345** [comment]
[{"id":"6cb8bd37-f8ae-4a6b-a236-3bab1b65cd8d","parentId":"0","name":"整形","sonValue":[{"id":"d4b6d3af-2edb-44a5-9851-c8964cf10d2c","parentId":"6cb8bd37-f8ae-4a6b-a236-3bab1b65cd8d","name":"眼部整形","sonValue":[{"id":"e531e96f-a081-40a7-a133-091be46983a2","parentId":"d4b6d3af-2edb-44a5-9851-c8964cf10d2c","name":"双眼皮","sonValue":[]}]},{"id":"403d93d3-5302-4682-a988-6dbfbe7ff563","parentId":"6cb8bd37-f8ae-4a6b-a236-3bab1b65cd8d","name":"胸部整形","sonValue":[{"id":"46afdd93-c830-4d0d-bd5d-c0751a0c087a","parentId":"403d93d3-5302-4682-a988-6dbfbe7ff563","name":"丰胸","sonValue":[{"id":"127a3cda-cd91-48b5-997c-6d56a4a02e80","parentId":"46afdd93-c830-4d0d-bd5d-c0751a0c087a","name":"自体脂肪丰胸","sonValue":[]}]}]}]},{"id":"a4f22a1a-0c49-46cd-bb1f-ca551b1e01cb","parentId":"0","name":"皮肤","sonValue":[{"id":"dfa5137c-616b-403c-a552-164e05518072","parentId":"a4f22a1a-0c49-46cd-bb1f-ca551b1e01cb","name":"脱毛美容","sonValue":[]},{"id":"bfd1eb85-93c1-489e-acba-ac3e783c83f0","parentId":"a4f22a1a-0c49-46cd-bb1f-ca551b1e01cb","name":"艺术纹绣","sonValue":[]}]}]

**Comment by IceApriler** [comment]
@zhzw345 你好，已经修复了哈，issue已自动关闭，你可以下载1.0.7尝试一下，有问题直接提~

https://github.com/IceApriler/miniprogram-picker/releases/tag/1.0.7

**Comment by zhzw345** [comment]
hi，刚刚下载替换，已经可以了，非常感谢，很高兴用到你的插件在项目中，及时雨 




------------------ 原始邮件 ------------------
发件人: "April"<notifications@github.com>;
发送时间: 2019年7月26日(星期五) 中午11:30
收件人: "IceApriler/miniprogram-picker"<miniprogram-picker@noreply.github.com>;
抄送: "Zhang"<249475586@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [IceApriler/miniprogram-picker] 只有两级的时候，没有清除原来选择的四级 (#2)




@zhzw345 你好，已经修复了哈，issue已自动关闭，你可以下载1.0.7尝试一下，有问题直接提~
 
https://github.com/IceApriler/miniprogram-picker/releases/tag/1.0.7
