### ISSUE TITLE
问下如果有一个联动是4级 有一个联动是5级 这种有办法嘛

### ISSUE THREAD

**Issue by 1519256257** [IceApriler/miniprogram-picker#4]
就是steps这个是不定的有的有下一级 有的没有 怎么办

**Comment by IceApriler** [comment]
你好，这个应该是支持的，你可以设置steps为5，如果有的数据只有四级，或者三级，我会自动填充到五级，只不过都是空。你可以试试，前几天刚完善好~

**Comment by 1519256257** [comment]
嗯  看到了。 就是会报警告 我去源码里吧警告屏蔽了就可以了 谢谢啦
